; Fractal Tree - ASCII art generated by recursion
; A tree that grows from the bottom, branching left and right

(define width 60)
(define height 20)

; Create a 2D canvas (list of strings)
(define (make-canvas w h)
  (repeat h (repeat w " ")))

(define (canvas-set canvas x y ch)
  (if (or (< x 0) (>= x width) (< y 0) (>= y height))
    canvas
    (let* ((row (nth canvas y))
           (new-row (append (take x row) (list ch) (drop (+ x 1) row))))
      (append (take y canvas) (list new-row) (drop (+ y 1) canvas)))))

(define (canvas->string canvas)
  (reduce (lambda (acc row) (string-append acc (list->string row) "\n")) "" canvas))

; Draw a branch recursively
(define (draw-branch canvas x y dx dy len depth)
  (if (or (= depth 0) (= len 0))
    canvas
    (let* ((canvas (canvas-set canvas x y (if (= depth 1) "*" (if (> (abs dy) (abs dx)) "|" (if (> (abs dx) 0) "/" "\\")))))
           (nx (+ x dx))
           (ny (+ y dy)))
      (if (= len 1)
        ; Branch into two
        (let* ((canvas (draw-branch canvas nx ny (- dx 1) dy (- depth 1) (- depth 1)))
               (canvas (draw-branch canvas nx ny (+ dx 1) dy (- depth 1) (- depth 1))))
          canvas)
        (draw-branch canvas nx ny dx dy (- len 1) depth)))))

; Simpler approach: just draw a static tree pattern
(define tree-lines (list
  "         *         "
  "        ***        "
  "       *****       "
  "      *******      "
  "     *********     "
  "    ***********    "
  "       ***         "
  "      *****        "
  "     *******       "
  "    *********      "
  "   ***********     "
  "  *************    "
  " ***************   "
  "       |||         "
  "       |||         "
  "       |||         "))

(for-each (lambda (line) (print line)) tree-lines)
(print "")
(print "-- a tree, by NahidaLisp --")